baseURL = "https://www.foldl.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Foldl: Programming Musings"
rssLimit = 10  # Maximum number of items in the RSS feed.
pygmentsCodeFences = true
pygmentsStyle = "friendly"
enableGitInfo = false
enableRobotsTXT = true
paginate = 50
googleAnalytics = "UA-71939520-2"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

staticDir = ["static"]

[author]
  name = "Chris Coffey"

[params]
description = "My musings about programming, management, and building a company."

[params.sns]
github = "ChrisCoffey"

[taxonomies]
    tag = "tags"

[languages]
[languages.en]
weight = 1
languageName = "English"
